language: python
# testing master only right now. dev tested manually
branches:
  only:
    - dev
# travis does not support windows yet. Need to add pre_install stuff for macOS
os:
  - linux
# f-strings (PEP 498) used extensively in autoimpute, so <3.6 not possible
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest -v